/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    midias: Midia;
    categorias: Categoria;
    lojas: Loja;
    produtos: Produto;
    avaliacoes: Avaliacoe;
    paginas: Pagina;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    midias: MidiasSelect<false> | MidiasSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    lojas: LojasSelect<false> | LojasSelect<true>;
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    avaliacoes: AvaliacoesSelect<false> | AvaliacoesSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'configuracoes-site': ConfiguracoesSite;
  };
  globalsSelect: {
    'configuracoes-site': ConfiguracoesSiteSelect<false> | ConfiguracoesSiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nome?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midias".
 */
export interface Midia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nome: string;
  /**
   * Identificador usado na URL publica.
   */
  slug: string;
  descricao?: string | null;
  tipo: 'produtos' | 'avaliacoes' | 'ambos';
  imagem?: (number | null) | Midia;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas".
 */
export interface Loja {
  id: number;
  nome: string;
  /**
   * Identificador usado na URL publica.
   */
  slug: string;
  tipo: 'marketplace' | 'produto_digital' | 'outro';
  url_base?: string | null;
  logo?: (number | null) | Midia;
  descricao?: string | null;
  ativa?: boolean | null;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  titulo: string;
  /**
   * Identificador usado na URL publica.
   */
  slug: string;
  resumo: string;
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categoria: number | Categoria;
  loja: number | Loja;
  link_afiliado: string;
  preco?: string | null;
  preco_promocional?: string | null;
  tipo_produto: 'fisico' | 'digital' | 'servico';
  imagem?: (number | null) | Midia;
  imagens?: (number | Midia)[] | null;
  /**
   * Exemplo: Mais vendido, Oferta relampago, Melhor custo-beneficio.
   */
  selo?: string | null;
  nota?: number | null;
  vantagens?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  desvantagens?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  destaque?: boolean | null;
  aviso_afiliado?: boolean | null;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avaliacoes".
 */
export interface Avaliacoe {
  id: number;
  titulo: string;
  /**
   * Identificador usado na URL publica.
   */
  slug: string;
  resumo: string;
  conteudo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categoria: number | Categoria;
  produtos_relacionados?: (number | Produto)[] | null;
  imagem?: (number | null) | Midia;
  autor?: string | null;
  tempo_leitura?: number | null;
  perguntas_frequentes?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  publicado_em?: string | null;
  destaque?: boolean | null;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  /**
   * Identificador usado na URL publica.
   */
  slug: string;
  resumo?: string | null;
  conteudo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    titulo?: string | null;
    descricao?: string | null;
    imagem?: (number | null) | Midia;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'midias';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'lojas';
        value: number | Loja;
      } | null)
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'avaliacoes';
        value: number | Avaliacoe;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midias_select".
 */
export interface MidiasSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  descricao?: T;
  tipo?: T;
  imagem?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas_select".
 */
export interface LojasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  tipo?: T;
  url_base?: T;
  logo?: T;
  descricao?: T;
  ativa?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  descricao?: T;
  categoria?: T;
  loja?: T;
  link_afiliado?: T;
  preco?: T;
  preco_promocional?: T;
  tipo_produto?: T;
  imagem?: T;
  imagens?: T;
  selo?: T;
  nota?: T;
  vantagens?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  desvantagens?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  destaque?: T;
  aviso_afiliado?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avaliacoes_select".
 */
export interface AvaliacoesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  conteudo?: T;
  categoria?: T;
  produtos_relacionados?: T;
  imagem?: T;
  autor?: T;
  tempo_leitura?: T;
  perguntas_frequentes?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  publicado_em?: T;
  destaque?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  conteudo?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-site".
 */
export interface ConfiguracoesSite {
  id: number;
  nome_site: string;
  url_site?: string | null;
  descricao_padrao?: string | null;
  aviso_afiliado_padrao?: string | null;
  redes_sociais?: {
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes-site_select".
 */
export interface ConfiguracoesSiteSelect<T extends boolean = true> {
  nome_site?: T;
  url_site?: T;
  descricao_padrao?: T;
  aviso_afiliado_padrao?: T;
  redes_sociais?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        tiktok?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}